[package]
name = "digit_recognizer_mnist"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = "4.5.4"
flate2 = "1.0.30"
log = "0.4.21"
nalgebra = "0.32.5"
ndarray = "0.15.6"
pretty_env_logger = "0.5.0"
